[package]
name = "gores_trainer"
version = "0.3.0"
edition = "2021"
public = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game_state_machine = "1.0.0"
ggez = "0.7.0"
rand = "0.8.5"
