name: Publish release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Rename config
      run: cp ./assets/default_config.toml ./config.toml

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./config.toml
        asset_name: config.toml
        asset_content_type: application/toml

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install ALSA dev
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev libudev-dev pkg-config libgl1-mesa-dev libxi-dev

    - uses: actions/checkout@v2

    - name: Run tests
      run: cargo test --verbose

    - name: Run build
      run: cargo build --release && strip --strip-all ./target/release/gores_trainer && mv ./target/release/gores_trainer ./target/release/gores_trainer-linux

    - name: Upload release
      id: upload-release-linux
      uses: alexellis/upload-assets@0.2.3
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_paths: '["./target/release/gores_trainer-linux"]'

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: cargo test --verbose

    - name: Run build
      run: cargo build --release && mv ./target/release/gores_trainer ./target/release/gores_trainer-macos

    - name: Upload release
      id: upload-release-linux
      uses: alexellis/upload-assets@0.2.3
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_paths: '["./target/release/gores_trainer-macos"]'


  build-windows:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: cargo test --verbose

    - name: Run build
      run: cargo build --release

    - name: Upload release
      id: upload-release-windows
      uses: alexellis/upload-assets@0.2.3
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_paths: '["./target/release/gores_trainer.exe"]'
